[package]
name = "rendiff"
version = "0.1.0"
edition = "2021"
rust-version = "1.69.0"
description = "Image comparison (diffing) for computer graphics renderer test cases."
license = "MIT OR Apache-2.0"
categories = ["development-tools::testing", "game-development", "multimedia::images", "rendering"]

[dependencies]
image = { version = "0.24.6", default-features = false }
itertools = { version = "0.10.5", default-features = false, features = ["use_alloc"] }
